### ISSUE TITLE
no icon on Gnome 3.32

### ISSUE THREAD

**Issue by legluondunet** [jenspfahl/KeepAwake#22]
Hello,
does this extension works on GNome 3.32? I have no icon since I upgraded to Ubuntu 19.04.
Thank you for your help.

**Comment by digitaleagle** [comment]
I have the same issue.  I installed Ubuntu 19.04 from scratch.  It was showing fine on my old installation of 18.10.

**Comment by Eeemil** [comment]
Since this repository hasn't been updated in ~2 years, and the author writes [the following on his website](https://jepfa.de/12/projects/keepawake/)
> As I hadn’t noticed from Caffeine, I started writing my own Gnome Shell Extension to prevent my computer going to sleep/hibernate mode.

Combined with [a 1 year old unattended PR](https://github.com/jenspfahl/KeepAwake/pull/18), I think the chances are slim that this will be fixed...

However, the suggested alternative, [Caffeine](https://extensions.gnome.org/extension/517/caffeine/) seems to work for me in Gnome 3.32 on Ubuntu 19.04.

@jenspfahl , do you have any intentions on continuing this project? If not, it would be great if you could deprecate it on extensions.gnome.org and/or point people towards Caffeine.

**Comment by jenspfahl** [comment]
Fixed with the new version 4, available on extensions.gnome.org
